version: '3.1'

services:
  db:
    image: postgres:15
    container_name: ticketing-app
    restart: always
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: ticketing_user
      POSTGRES_PASSWORD: ticketing_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
